const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    AUTHENTICATION_ERROR: 4,
    FILESYSTEM_ERROR: 5,
    NETWORK_ERROR: 6,
    PERMISSIONS_ERROR: 7,
    CONFIGURATION_ERROR: 8,
    SECURITY_ERROR: 9
};

export default EErrors;
